title: Mirko brombin
description: 
author: Mirko brombin
email: send@mirko.pm

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  - projects
  - bookmarks

plugins:
  - jekyll-feed