title: Mirko brombin
description: 
author: Mirko brombin
email: send@mirko.pm

assets: /assets
uploads: /uploads

markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed