title: linux/hub
description: Guide curate e dettagliate sul mondo Linux ed Open source. Trattiamo nello specifico argomenti a scopo educativo.
author: linuxhub.it Team
email: send@mirko.pm

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

pagination:
  enabled: true
  collection: 'posts'
  per_page: 11
  permalink: '/posts/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'published'
  sort_reverse: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation:
    - link: "/"
      name: Educazione per Linux ed Open source

plugins:
  - jekyll-feed
  - jekyll-paginate-v2